from setuptools import setup

package_name = "unoq_braccio_driver"

setup(
    name=package_name,
    version="0.1.0",
    packages=[package_name],
    package_data={package_name: ["web/*.html", "web/*.css", "web/*.js", "web/*.svg", "web/vendor/*"]},
    data_files=[
        ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
        (f"share/{package_name}", ["package.xml"]),
    ],
    install_requires=["setuptools", "pyserial", "PyYAML"],
    zip_safe=True,
    maintainer="Eoin Jordan",
    maintainer_email="eoin@example.com",
    description="Arduino UNO serial bridge, vision, teaching and web dashboard for the Braccio.",
    license="MIT",
    entry_points={
        "console_scripts": [
            "serial_bridge = unoq_braccio_driver.serial_bridge:main",
            "tcp_bridge = unoq_braccio_driver.tcp_bridge:main",
            "pose_demo = unoq_braccio_driver.pose_demo:main",
            "edge_impulse_mapper = unoq_braccio_driver.edge_impulse_mapper:main",
            "edge_impulse_vision = unoq_braccio_driver.edge_impulse_vision:main",
            "detection_label_bridge = unoq_braccio_driver.detection_label_bridge:main",
            "edge_impulse_capture = unoq_braccio_driver.edge_impulse_capture:main",
            "pick_place_executor = unoq_braccio_driver.pick_place_executor:main",
            "usb_camera_node = unoq_braccio_driver.usb_camera_node:main",
            "mjpeg_camera_node = unoq_braccio_driver.mjpeg_camera_node:main",
            "color_tracker = unoq_braccio_driver.color_tracker:main",
            "visual_servo_assist = unoq_braccio_driver.visual_servo_assist:main",
            "joint_state_simulator = unoq_braccio_driver.joint_state_simulator:main",
            "joint_trajectory_bridge = unoq_braccio_driver.joint_trajectory_bridge:main",
            "ik_pose_demo = unoq_braccio_driver.ik_pose_demo:main",
            "sim_cube_detector = unoq_braccio_driver.sim_cube_detector:main",
            "sim_gripper_detector = unoq_braccio_driver.sim_gripper_detector:main",
            "camera_node = unoq_braccio_driver.camera_node:main",
            "download_model = unoq_braccio_driver.download_model:main",
            "real_setup = unoq_braccio_driver.real_setup:main",
            "arm_tricks = unoq_braccio_driver.arm_tricks:main",
            "sim_grasp_attacher =unoq_braccio_driver.sim_grasp_attacher:main",
            "workspace_markers = unoq_braccio_driver.workspace_markers:main",
            "pick_place_demo = unoq_braccio_driver.pick_place_demo:main",
            "manual_control = unoq_braccio_driver.manual_control:main",
            "gui_to_joint_command = unoq_braccio_driver.gui_to_joint_command:main",
            "teach_pick = unoq_braccio_driver.teach_pick:main",
            "learned_pick_demo = unoq_braccio_driver.learned_pick_demo:main",
            "web_dashboard = unoq_braccio_driver.web_dashboard:main",
        ],
    },
)
